# Generated by Django 2.0.4 on 2018-07-17 21:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20180717_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketinfo',
            name='low',
            field=models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36),
        ),
    ]
