# Generated by Django 2.0.4 on 2018-07-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_marketinfo_low'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='independent_reserve_marketinfo',
            name='marketinfo_ptr',
        ),
        migrations.DeleteModel(
            name='independent_reserve_marketinfo',
        ),
        migrations.DeleteModel(
            name='marketinfo',
        ),
    ]
