# Generated by Django 2.0.4 on 2018-07-24 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_auto_20180719_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='cloud_transaction',
            new_name='cloud_transaction_id',
        ),
    ]
