# Generated by Django 2.0.4 on 2018-07-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_auto_20180724_2040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='independent_reserve_marketinfo',
            new_name='independent_reserve_marketdata',
        ),
    ]
