# Generated by Django 2.0.4 on 2018-05-30 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MarketInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_pair', models.CharField(max_length=40)),
                ('miscellaneous', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bits', models.BinaryField()),
                ('is_compiled', models.BooleanField(default=False)),
                ('compilation_result', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('language', models.ForeignKey(db_column='language_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='back.Language')),
                ('user', models.ForeignKey(db_column='user_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_transaction_id', models.CharField(max_length=40)),
                ('managers_pair_symbol', models.CharField(max_length=40)),
                ('market_action', models.CharField(max_length=4)),
                ('primary_security', models.CharField(max_length=4)),
                ('secondary_security', models.CharField(max_length=4)),
                ('received_amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('given_amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('date', models.DateField()),
                ('current_exposure', models.DecimalField(decimal_places=18, max_digits=36)),
                ('user', models.ForeignKey(db_column='user_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.ForeignKey(db_column='strategy_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='back.Strategy')),
                ('user', models.ForeignKey(db_column='user_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
