# Generated by Django 2.0.4 on 2018-06-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='cloud_transaction_id',
            new_name='cloud_transaction',
        ),
    ]
